// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Timeless Strokes",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Timeless Strokes",
            targets: ["AppModule"],
            bundleIdentifier: "gustvtech.TimelessStrokes",
            teamIdentifier: "XS79B5ZKN3",
            displayVersion: "2.1",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .palette),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            appCategory: .kidsGames
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)